import { money } from "./format.js";

const APP_NAME = "ProfitDoctor";

/**
 * A plain-text summary a merchant can paste into Slack/email — deliberately
 * not a PDF or a hosted link: nothing about the scan is stored anywhere,
 * so there's nothing to link to.
 */
export function buildShareSummary(report, { isDemo = false } = {}) {
  const lines = [];
  lines.push(`${APP_NAME} Margin Scan${isDemo ? " (demo data)" : ""}`);
  lines.push(`${report.headline.leaksCount} potential margin leak${report.headline.leaksCount === 1 ? "" : "s"} detected`);
  if (report.headline.knownMarginAtRisk > 0) {
    lines.push(`${money(report.headline.knownMarginAtRisk, report.currency)} known product margin at risk`);
  }
  lines.push("");

  for (const leak of report.leaks) {
    const impact = leak.knownProductMargin !== null ? money(leak.knownProductMargin, report.currency) : "UNKNOWN";
    lines.push(`${leak.severity} — ${leak.title}: ${impact} — ${leak.whatWeFound}`);
  }

  lines.push("");
  lines.push("Not included: payment fees, advertising, fulfillment, actual shipping cost, returns.");
  lines.push(`Generated by ${APP_NAME} (prototype) — a free, self-service Shopify margin leak scanner.`);

  return lines.join("\n");
}
